version: "3.9"
services:
  mcp-trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-trader
    environment:
      - QC_USER_ID=${QC_USER_ID}
      - QC_TOKEN=${QC_TOKEN}
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
