name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      QC_TOKEN: ${{ secrets.QC_TOKEN }}
      QC_ORG_ID: ${{ secrets.QC_ORG_ID }}
    steps:
      - name: Check secrets
        run: |
          echo "Testing if secrets are available..."
          if [ -z "$QC_TOKEN" ]; then
            echo "❌ ERROR: QC_TOKEN is empty!"
          else
            echo "✅ QC_TOKEN is set (length: ${#QC_TOKEN})"
          fi
          
          if [ -z "$QC_ORG_ID" ]; then
            echo "❌ ERROR: QC_ORG_ID is empty!"
          else
            echo "✅ QC_ORG_ID is set (value: $QC_ORG_ID)"
          fi
          
          # Test if secrets match expected lengths
          if [ ${#QC_TOKEN} -eq 64 ]; then
            echo "✅ QC_TOKEN has correct length (64 chars)"
          else
            echo "❌ QC_TOKEN has wrong length: ${#QC_TOKEN}"
          fi
          
          if [ ${#QC_ORG_ID} -eq 32 ]; then
            echo "✅ QC_ORG_ID has correct length (32 chars)"
          else
            echo "❌ QC_ORG_ID has wrong length: ${#QC_ORG_ID}"
          fi