name: Iron Condor Backtest (Working)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  backtest:
    runs-on: ubuntu-latest
    env:
      QC_TOKEN: ${{ secrets.QC_TOKEN }}
      QC_ORG_ID: ${{ secrets.QC_ORG_ID }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install Lean CLI
        run: pip install --upgrade lean
        
      - name: Verify Secrets
        run: |
          echo "✅ QC_TOKEN length: ${#QC_TOKEN}"
          echo "✅ QC_ORG_ID: $QC_ORG_ID"
          
      - name: Login to QuantConnect
        run: |
          echo "🔑 Logging in to QuantConnect..."
          lean login --user-id "386972" --api-token "$QC_TOKEN"
          lean whoami
          echo "✅ Login successful"
          
      - name: Update Lean Config
        run: |
          echo "📝 Updating lean.json with organization ID..."
          sed -i "s/\"organization-id\": \"\"/\"organization-id\": \"$QC_ORG_ID\"/g" lean.json
          sed -i "s/\"job-organization-id\": \"\"/\"job-organization-id\": \"$QC_ORG_ID\"/g" lean.json
          echo "✅ Configuration updated"
          
      - name: Push Project to Cloud
        run: |
          echo "📦 Pushing IronCondorTest project..."
          lean cloud push --project "IronCondorTest" --verbose
          echo "✅ Project pushed successfully"
          
      - name: Run Iron Condor Backtest
        timeout-minutes: 60
        run: |
          echo "🚀 Starting HV-7 Iron Condor backtest (1-hour timeout)..."
          lean cloud backtest "IronCondorTest" --open --verbose